---
max_mer: 5
pop: "AFR"
feature: "cpg_islands"
c: 0.04472136
set_sigma: 0.8540486
0:
  iteration_burnin:
    - 120000
    - 100000
  thinning_parameter: 10
  alpha: 0
  slab_sigma: 0
  proposal_sigmas:
    alpha_sigma: 0
    sigma_sigma: 0
    theta_sigma: 0.00005
    indicator_sampling: 'gibbs'
1:
  iteration_burnin:
    - 120000
    - 100000
  thinning_parameter: 10
  alpha: 0.99
  slab_sigma: 1.0
  proposal_sigmas:
    alpha_sigma: 'beta'
    sigma_sigma: 0.2
    theta_sigma: 0.001
    indicator_sampling: 'gibbs'
2:
  iteration_burnin:
    - 120000
    - 100000
  thinning_parameter: 10
  alpha: 0.8
  slab_sigma: 0.2
  proposal_sigmas:
    alpha_sigma: 'beta'
    sigma_sigma: 0.02
    theta_sigma: 0.005
    indicator_sampling: 'gibbs'
3:
  iteration_burnin:
    - 120000
    - 100000
  thinning_parameter: 10
  alpha: 0.8
  slab_sigma: 0.18
  proposal_sigmas:
    alpha_sigma: 'beta'
    sigma_sigma: 0.006
    theta_sigma: 0.005
    indicator_sampling: 'gibbs'
4:
  iteration_burnin:
    - 120000
    - 100000
  thinning_parameter: 10
  alpha: 0.6
  slab_sigma: 0.25
  proposal_sigmas:
    alpha_sigma: 'beta'
    sigma_sigma: 0.004
    theta_sigma: 0.005
    indicator_sampling: 'gibbs'
...
