## my yaml config file for generating all my files via the bash wrapper##
---
ancestral:
  True
genome_build:
  'GRCh38'
POP1:
  vcf_files:
    chr1: "tutorial_data/chr1.test_data.vcf.gz"
POP2:
  vcf_files:
    chr2: "tutorial_data/chr2.test_data.vcf.gz"
features:
  nc_accessibility_mask:
    bed: "tutorial_data/nc_accessibility_mask.bed"
    fastas: 
      chr1: "tutorial_data/nc_accessibility_mask.5_bp_buffer.homo_sapiens_ancestor_1.fa.gz"
      chr2: "tutorial_data/nc_accessibility_mask.5_bp_buffer.homo_sapiens_ancestor_2.fa.gz"
chromosomes:
  - "chr1"
  - "chr2"
...
