## my yaml config file for generating all my files via the bash wrapper##
---
ancestral:
  True
genome_build:
  'GRCh38'
AFR:
  vcf_files:
    chr1: "tutorial_data/chr1.AFR.cpg_islands.vcf.bgz"
EAS:
  vcf_files:
    chr1: "tutorial_data/chr1.EAS.cpg_islands.vcf.bgz"
features:
  cpg_islands:
    bed: "tutorial_data/cpg_islands.bed"
    fastas: 
      chr1: "tutorial_data/chr1.cpg_islands.ancestral.fa"
chromosomes:
  - "chr1"
...
